//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery : Comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.DetallesDeliveries = new HashSet<DetalleDelivery>();
        }
    
        public long ClienteId { get; set; }
        public decimal Total { get; set; }
        public string DireccionEnvio { get; set; }
        public string Observacion { get; set; }
        public EstadoDelivery EstadoDelivery { get; set; }
        public long CadeteId { get; set; }
        public decimal Descuento { get; set; }
        public decimal SubTotal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDelivery> DetallesDeliveries { get; set; }
        public virtual Empleado Cadete { get; set; }
    }
}
