//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public enum EstadoMesa : int
    {
        Libre = 1,
        Reservada = 2,
        Ocupada = 3,
        Reparacion = 4,
        Facturada = 5
    }
}
