//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public long Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public EstadoFactura Estado { get; set; }
        public decimal Total { get; set; }
        public int Numero { get; set; }
        public long EmpleadoId { get; set; }
        public long ClienteId { get; set; }
        public Nullable<long> CuentaCorrienteId { get; set; }
        public decimal TotalAbonado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual CuentaCorriente CuentaCorriente { get; set; }
        public virtual Comprobante Comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
