//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloGastronomiaContainer : DbContext
    {
        public ModeloGastronomiaContainer()
            : base("name=ModeloGastronomiaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Perfil> Perfiles { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Comprobante> Comprobantes { get; set; }
        public virtual DbSet<Mesa> Mesas { get; set; }
        public virtual DbSet<DetalleComprobante> DetalleComprobantes { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Rubro> Rubros { get; set; }
        public virtual DbSet<SubRubro> SubRubros { get; set; }
        public virtual DbSet<ListaPrecio> ListaPrecios { get; set; }
        public virtual DbSet<Alicuota> Alicuotas { get; set; }
        public virtual DbSet<ListaPrecioProducto> ListaPrecioProductos { get; set; }
        public virtual DbSet<CondicionIva> CondicionIvas { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<CuentaCorriente> CuentasCorriente { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<PedidoProducto> PedidosProducto { get; set; }
    }
}
