//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProducto
    {
        public long Id { get; set; }
        public int Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal PrecioCosto { get; set; }
        public int Cantidad { get; set; }
        public decimal Total { get; set; }
        public int ProductoId { get; set; }
        public long ProveedorId { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
