//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Persona
    {
        public long Id { get; set; }
        public string Direccion { get; set; }
        public string Teléfono { get; set; }
        public bool EstaEliminado { get; set; }
    }
}
